// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Analysis struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Image       string `json:"image"`
	Disabled    bool   `json:"disabled"`
}

type Hiw struct {
	ID          int    `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Image       string `json:"image"`
}
